FROM golang:1.20.1 AS builder

WORKDIR /root/

RUN go get github.com/google/trillian/cmd/createtree@v1.3.10
ADD ./config/logid.sh /root/
ADD ./config/ctfe /root/ctfe
RUN chmod +x /root/logid.sh

CMD /root/logid.sh
